### PR TITLE
Change account status

### PR DESCRIPTION
**Pull request by mugishaj092**
#### What does this PR do?
Admin should be able to disable an account for various reasons

#### Describe your changes
I add new endpoint to change status of account by admin

#### PR Type
What kind of change does this PR introduce?
```
[ x ] Feature
```

#### How should this be manually tested?
1.Pull the branch  
2.install dependencies  
3.run migrations  
4.start server  
5.You can use postman to test this endpoint http://localhost:${PORT}/api/users/change-account-status/:id

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/n/projects/2703465/stories/187570738)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by GabrielDushime — DISMISSED** [review]
Great job Bruh!Keep Working Hard

**Review by SHYAKA-Aime — APPROVED** [review]
Good to go, I can see you worked on the Changes requested👏

**Review by kennyg37 — CHANGES_REQUESTED** [review]
great pr however it is better that in our constants file every constant is in an object to minimize imports i.e put the two subjects and reason in one object

**Comment by mugishaj092** [comment]
> great pr however it is better that in our constants file every constant is in an object to minimize imports i.e put the two subjects and reason in one object

solve

**Review by mutsinziisaac — APPROVED** [review]
Good job

**Review by vegetason — APPROVED** [review]
I think  you have done well

**Review by GabrielDushime — APPROVED** [review]
Good you have worked on the requested change

**Review by kennyg37 — APPROVED** [review]
You fixed the issue, the pr is good to go

**Pull request merged**
