### PR TITLE
Add product wishlist

### PR DESCRIPTION
**Pull request by mugishaj092**
#### What does this PR do?
Add product on wishlist 
#### Describe your changes
i added endpoint help to add product on wishlist, it's test and i documented it using swagger
#### PR Type
What kind of change does this PR introduce?
```
[ x ] Feature
```

#### How should this be manually tested?

- pull changes
- run server
- test using sagger or postman
- run test

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/n/projects/2703465/stories/187570746)

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
Great that now a product can be added to a wishlist

**Review by GabrielDushime — CHANGES_REQUESTED** [review]
Resolve the conflicts and let all your test pass on circleci

**Review by mutsinziisaac — APPROVED** [review]

**Review by mutsinziisaac — CHANGES_REQUESTED** [review]
resolve conflicts

**Review by SHYAKA-Aime — CHANGES_REQUESTED** [review]
Fix CircleCi and codeclimate issues as well as resolving conflicts

**Pull request closed without merging**
