### PR TITLE
Fixing update role endpoint url and hide password in response

### PR DESCRIPTION
**Pull request by mugishaj092**
#### What does this PR do?
Fixing mistake was in updating role endpoint
#### Describe your changes
I make  some changes in response where i hide password in response and also i changed endpoint
#### PR Type
What kind of change does this PR introduce?
```
[ x ] Bugfix

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
Great you fixed the issue

**Review by SHYAKA-Aime — APPROVED** [review]
Good to fix that

**Review by mutsinziisaac — APPROVED** [review]
Great job on fixing this bug! The code looks clean and the solution is effective. Thanks for addressing this issue so quickly. Everything seems to work well on my end. Approved!

**Review by vegetason — APPROVED** [review]
I think you did well as you managed to add some required details in updating role endpoint

**Review by Mugisha146 — APPROVED** [review]

**Pull request merged**
