### PR TITLE
Update package.json: Correct errors and migrate from yarn to npm

### PR DESCRIPTION
**Pull request by mugishaj092**
This pull request for fixing package.json and migrate for from yarn to npm

### CODE REVIEW

**Review by mutsinziisaac — APPROVED** [review]
great!!  this was highly needed joseph

**Review by vegetason — APPROVED** [review]
Its' great that we will be using npm instead of yarn

**Review by GabrielDushime — APPROVED** [review]
Good Job Joseph!

**Comment by SHYAKA-Aime** [comment]
👍

**Pull request merged**
