### PR TITLE
Run codeclimate & test coverage after test run with CI

### PR DESCRIPTION
**Pull request by GabrielDushime**
I've set up a CI/CD pipeline with CircleCI and CodeClimate, integrated Mocha and Chai for testing, and ensured that your maintainability score is updated based on your test coverage.

I have made a change on this #PR  as requested to add .env to keep our environment variables

### CODE REVIEW

**Review by mugishaj092 — CHANGES_REQUESTED** [review]
.env.example is like blueprint of our .env you need to create file called .env and add those envirnoment variables.

**Review by mutsinziisaac — APPROVED** [review]
fix

**Comment by GabrielDushime** [comment]
> .env.example is like blueprint of our .env you need to create file called .env and add those envirnoment variables.

Already Created sir

**Review by kennyg37 — APPROVED** [review]
All good but be aware off possible conflict in package.json file

**Pull request merged**
