### PR TITLE
Mark-available-or-unvailable-product

### PR DESCRIPTION
**Pull request by Mugisha146**
#### What does this PR do?
A seller should mark available or unavailable product
#### Describe your changes
feature to mark available or unavailable 
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ *] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570741)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
I can see you worked on the task and also on the requested change!
Great work so far

**Review by mugishaj092 — APPROVED** [review]
You did great job

**Review by mugishaj092 — APPROVED** [review]

**Review by GabrielDushime — APPROVED** [review]
Good you solvedthe conflicts

**Review by vegetason — APPROVED** [review]
Good work

**Review by mutsinziisaac — APPROVED** [review]

**Review by SHYAKA-Aime — APPROVED** [review]
Running well, good job

**Pull request merged**
