### PR TITLE
User updating password

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
#### What does this PR do?
Helps a user to update his/her current password to a new password
#### Describe your changes
Added the functionality and tests for the endpoint as well as the Swagger Documentation 
#### PR Type
What kind of change does this PR introduce?
```

[ ] Feature

```

#### How should this be manually tested?
Navigate to the branch and Test the functionality either in Swagger UI or Postman
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570736)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by mugishaj092 — APPROVED** [review]
Great Job

**Review by kennyg37 — APPROVED** [review]
No issues the test coverage is also good but it could be better

**Review by vegetason — APPROVED** [review]
I think you did well as there is no issues seen in the code

**Review by mutsinziisaac — APPROVED** [review]

**Review by mugishaj092 — APPROVED** [review]
Great job

**Review by GabrielDushime — APPROVED** [review]
Great work on the changes

**Review by vegetason — APPROVED** [review]
I think there is no errors

**Comment by jamesndekezi** [comment]
Hey, well done on your changes

**Review by kennyg37 — APPROVED** [review]
good to go

**Review by jamesndekezi — APPROVED** [review]
Hey, well done with changes

**Pull request merged**
