### PR TITLE
fixed the login controller to disable deactivated accounts to Login

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
#### What does this PR do?
Bugfix for user login functionality to Avoid deactivated account to Login
#### Describe your changes
Added a check in Login route controller for the isActive status of the user before validating the password
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix

```

#### How should this be manually tested?
Using swagger doc or postman
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by mutsinziisaac — APPROVED** [review]

**Review by GabrielDushime — CHANGES_REQUESTED** [review]
Just make sure all test are running correctly to make your tests also run on circleci
WhatsApp Image 2024-06-03 at 22 26 28_dd9ecd3a

**Review by mugishaj092 — COMMENTED** [review]
Great work so far but all tests is not passing can you first solve that issue?

**Review by mugishaj092 — CHANGES_REQUESTED** [review]
Great work so far but all tests is not passing can you first solve that issue?

**Review by mutsinziisaac — APPROVED** [review]

**Comment by SHYAKA-Aime** [comment]
> Just make sure all test are running correctly to make your tests also run on circleci WhatsApp Image 2024-06-03 at 22 26 28_dd9ecd3a

Solved

**Comment by SHYAKA-Aime** [comment]
> Great work so far but all tests is not passing can you first solve that issue?

Solved

**Review by Mugisha146 — APPROVED** [review]
i see now test are passing so far i don't see any problem good job

**Review by GabrielDushime — DISMISSED** [review]
Great you solved the conflicts

**Review by GabrielDushime — APPROVED** [review]
Great you are being able to solve the conflict

**Review by vegetason — APPROVED** [review]
I think you did well

**Review by mutsinziisaac — APPROVED** [review]

**Review by mugishaj092 — APPROVED** [review]

**Pull request merged**
