### PR TITLE
Ft user login email pwd

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
#### What does this PR do?
It contains a feature for User login with Email and Password
#### Describe your changes
I created a route and it's corresponding controller to handle login with email and password, I also wrote the tests and documented the route with Swagger
#### PR Type
What kind of change does this PR introduce?
```
[ ] Feature
```

#### How should this be manually tested?
1.Pull the branch
2.install dependencies
3.create migrations
4.start server
5.run tests
5.You can use either postman or Swagger UI documentation  ``` /api/users/login```  to test this functionality
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570731)

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
Good

**Review by mutsinziisaac — APPROVED** [review]
👍🏾

**Review by kennyg37 — APPROVED** [review]
Looks great

**Review by furebo — CHANGES_REQUESTED** [review]
The deployment is failing because the Typescript compiler is not found  . Try to add this  
- run:
          name: Compile TypeScript
          command: ./node_modules/.bin/tsc
in .circleci -> config.yml file in deploy step after running tests to fix it.

**Review by mugishaj092 — APPROVED** [review]
Great job

**Pull request merged**
