### PR TITLE
add production server on swagger

### PR DESCRIPTION
**Pull request by mugishaj092**
#### Describe your changes
i added production server in swagger documentation

#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
```

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
Good job to the the swagger

**Review by mutsinziisaac — APPROVED** [review]
Easy peasy

**Review by SHYAKA-Aime — APPROVED** [review]
great work, Ready to go

**Review by kennyg37 — APPROVED** [review]
This fixes the issue this PR can be merged

**Pull request merged**
