### PR TITLE
[#187570743]A User should be able to view a specific item

### PR DESCRIPTION
**Pull request by vegetason**
#### What does this PR do?
  User should be able to view a specific item
#### Describe your changes
 -endpoints for a seller to view products in his collection
 -endpoint for a buyer to view products in available products
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[*] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?

It can be tested in swagger documentation

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/n/projects/2703465/stories/187570743)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by GabrielDushime — APPROVED** [review]
Good you corrected the issue

**Review by Mugisha146 — DISMISSED** [review]

**Review by jamesndekezi — DISMISSED** [review]
Well done

**Comment by jamesndekezi** [comment]
> Well done, so finish it so it can be merged

**Review by GabrielDushime — COMMENTED** [review]
Good work

**Review by GabrielDushime — APPROVED** [review]

**Review by kennyg37 — DISMISSED** [review]

**Review by SHYAKA-Aime — CHANGES_REQUESTED** [review]
View product must be a get request not a Post request

**Review by GabrielDushime — DISMISSED** [review]
Great that you worked on the requested changes from post to get request for a seller to be able to view a specific item

**Review by GabrielDushime — DISMISSED** [review]

**Review by GabrielDushime — APPROVED** [review]

**Review by jamesndekezi — APPROVED** [review]
Here's a short comment for the review:

---

The PR looks good overall, with well-implemented functionality for viewing specific products and products by seller. Comprehensive tests and robust error handling are included. Good job!

**Review by SHYAKA-Aime — APPROVED** [review]
Working well, good to go

**Pull request merged**
