### PR TITLE
The products should stop listing if the expiry date has passed

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
#### What does this PR do?
This PR Includes funtionality and tests for checking if product has expired and stop it from listing in available products
#### Describe your changes
Added a cronjob and eventEmitter that runs everyday to check if the product expire date has reached, if it is expired, the expired flag is set to true and availability is set to false which will remove it in available products list.
#### PR Type
What kind of change does this PR introduce?
```
[ ] Feature

```

#### How should this be manually tested?
1.Run migrations
2.Run tests
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570757)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by mutsinziisaac — APPROVED** [review]
good job

**Review by GabrielDushime — APPROVED** [review]
Great Job So far

**Review by vegetason — APPROVED** [review]
Good job on this PR, the code is clean and easy to understand

**Review by jamesndekezi — APPROVED** [review]
I tested your feature and it functions as expected. Great job!

**Review by Mugisha146 — APPROVED** [review]
Good job brother

**Pull request merged**
