### PR TITLE
Fixing Issues With Houndci And Codeclimate on our project

### PR DESCRIPTION
**Pull request by GabrielDushime**
Avoiding running two test coverage reporter to Our Project And the issue related to similar code in code climate and houndci

[ ] Bugfix

### CODE REVIEW

**Review by vegetason — DISMISSED** [review]
Well done on fixing the hound bot issues

**Review by kennyg37 — APPROVED** [review]
Good to see the Houndci issues solved

**Review by mugishaj092 — APPROVED** [review]

**Review by SHYAKA-Aime — APPROVED** [review]
Looks great

**Review by kennyg37 — APPROVED** [review]
Good to go, i think issues with houndci are fixed

**Pull request merged**
