### PR TITLE
mark notifications as read

### PR DESCRIPTION
**Pull request by mutsinziisaac**
#### What does this PR do?
add marking notifications 

#### Describe your changes
users will be able to mark one or more notifications as read

#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[# ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?
using swagger doc or npm test

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/187570756

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by GabrielDushime — DISMISSED** [review]
Great job so far

**Review by SHYAKA-Aime — DISMISSED** [review]

**Review by vegetason — DISMISSED** [review]
Well done. The functionalities work as expected.

**Review by kennyg37 — DISMISSED** [review]

**Review by Mugisha146 — APPROVED** [review]
Well done

**Review by jamesndekezi — APPROVED** [review]
Nicely done

**Review by GabrielDushime — APPROVED** [review]

**Review by SHYAKA-Aime — APPROVED** [review]

**Review by mugishaj092 — APPROVED** [review]

**Pull request merged**
