### PR TITLE
Buyer should be able to track their order status

### PR DESCRIPTION
**Pull request by SHYAKA-Aime**
#### What does this PR do?
Allowing buyer to be able to track their order status and admin to update the order status
#### Describe your changes
Functionality, Documentation and tests of the feature
#### PR Type
What kind of change does this PR introduce?
```
[ ] Feature

```

#### How should this be manually tested?
Using swagger Documentation or Jest tests
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570753)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by Mugisha146 — APPROVED** [review]
Great job

**Review by mutsinziisaac — APPROVED** [review]

**Review by mugishaj092 — APPROVED** [review]
Great job

**Review by GabrielDushime — APPROVED** [review]
Great job so far now Buyer should be able to track their order status

**Review by vegetason — APPROVED** [review]
well done

**Review by jamesndekezi — APPROVED** [review]
Well done

**Pull request merged**
