### PR TITLE
searching feature

### PR DESCRIPTION
**Pull request by mutsinziisaac**
#### What does this PR do?
add searching feature on products
#### Describe your changes
the user should be able to search and filter products
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[* ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?
using the search endpoint in the product controller
#### What are the relevant pivotal tracker stories?
[[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)](https://www.pivotaltracker.com/story/show/187570752)

#### Screenshots (if is appropriate)

### CODE REVIEW

**Review by SHYAKA-Aime — DISMISSED** [review]
Great, but It would be better if you change the getProducts function in product services to getAllProducts

**Review by GabrielDushime — DISMISSED** [review]
Great work so far now a user can search a product

**Review by kennyg37 — APPROVED** [review]

**Review by vegetason — APPROVED** [review]
I tested your feature, and they work as expected ,well done

**Review by GabrielDushime — APPROVED** [review]
Great work you solved the conflicts and now a user is able to search an item

**Review by jamesndekezi — APPROVED** [review]
I tested your feature, and it functions perfectly as intended. Excellent work!

**Review by Mugisha146 — APPROVED** [review]

**Pull request merged**
