### PR TITLE
Initial commit: Set up empty Node.js Express application structure an…

### PR DESCRIPTION
**Pull request by mugishaj092**
**## Pull Request Description**

This pull request establishes the initial structure for our Node.js Express application. The directory layout includes folders such as `src/` with subdirectories for `controllers`, `models`, `routes`, `services`, `utils`, `__test__`, and `validations`. Additionally, I've created some files in the root folder such as `.env.example`, `Convention.md`, and `dotenv_usage.md`.

Furthermore, I've integrated `dotenv` for managing environment variables in our API. This ensures that packages like `sequelize` and `passport` can fetch data about the current environment correctly via `dotenv`.

Please review the changes and provide any feedback or suggestions for improvement.
****

### CODE REVIEW

**Comment by GabrielDushime** [comment]
Great work

**Comment by SHYAKA-Aime** [comment]
Awesome👍

**Comment by GabrielDushime** [comment]
Great Work Brother Keep pushing

**Review by kennyg37 — APPROVED** [review]
Great work, but if its possible can you make sure that the only viable package manager is not yarn so that those who prefer npm don't face issues. Besides that everything is good

**Review by SHYAKA-Aime — APPROVED** [review]
Great , The structure is complete

**Review by vegetason — APPROVED** [review]
I think you did well

**Pull request merged**
